<!-- create a promise which rejects after 3 sec use an async/await to gets its value. use a try catch to handle its error -->


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>

  <script>
    let p = () => {
      return new Promise((resolve, reject){
        setTimeout(() => {
          reject("error")
        }, 3000)
      })
    }

    let a = async () => {
      try {
        let c = await p();
        console.log(c);
      } catch (error) {
        console.log(error);
      }
    }



  </script>
</body>

</html>